# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: basics.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x62\x61sics.proto\x12\x03\x64pa\"!\n\x0bPingRequest\x12\x12\n\nclient_msg\x18\x01 \x01(\t\"A\n\x0cPongResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x12\n\nclient_msg\x18\x02 \x01(\t\x12\r\n\x05\x63ount\x18\x03 \x01(\x05\x32\x38\n\x05\x42\x61sic\x12/\n\x06\x44oPing\x12\x10.dpa.PingRequest\x1a\x11.dpa.PongResponse\"\x00\x62\x06proto3')



_PINGREQUEST = DESCRIPTOR.message_types_by_name['PingRequest']
_PONGRESPONSE = DESCRIPTOR.message_types_by_name['PongResponse']
PingRequest = _reflection.GeneratedProtocolMessageType('PingRequest', (_message.Message,), {
  'DESCRIPTOR' : _PINGREQUEST,
  '__module__' : 'basics_pb2'
  # @@protoc_insertion_point(class_scope:dpa.PingRequest)
  })
_sym_db.RegisterMessage(PingRequest)

PongResponse = _reflection.GeneratedProtocolMessageType('PongResponse', (_message.Message,), {
  'DESCRIPTOR' : _PONGRESPONSE,
  '__module__' : 'basics_pb2'
  # @@protoc_insertion_point(class_scope:dpa.PongResponse)
  })
_sym_db.RegisterMessage(PongResponse)

_BASIC = DESCRIPTOR.services_by_name['Basic']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PINGREQUEST._serialized_start=21
  _PINGREQUEST._serialized_end=54
  _PONGRESPONSE._serialized_start=56
  _PONGRESPONSE._serialized_end=121
  _BASIC._serialized_start=123
  _BASIC._serialized_end=179
# @@protoc_insertion_point(module_scope)
