# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cluster.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcluster.proto\x12\x03\x64pa\x1a\x1bgoogle/protobuf/empty.proto\" \n\rLeaderDetails\x12\x0f\n\x07node_id\x18\x01 \x01(\t2D\n\x07\x43luster\x12\x39\n\tGetLeader\x12\x16.google.protobuf.Empty\x1a\x12.dpa.LeaderDetails\"\x00\x62\x06proto3')



_LEADERDETAILS = DESCRIPTOR.message_types_by_name['LeaderDetails']
LeaderDetails = _reflection.GeneratedProtocolMessageType('LeaderDetails', (_message.Message,), {
  'DESCRIPTOR' : _LEADERDETAILS,
  '__module__' : 'cluster_pb2'
  # @@protoc_insertion_point(class_scope:dpa.LeaderDetails)
  })
_sym_db.RegisterMessage(LeaderDetails)

_CLUSTER = DESCRIPTOR.services_by_name['Cluster']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LEADERDETAILS._serialized_start=51
  _LEADERDETAILS._serialized_end=83
  _CLUSTER._serialized_start=85
  _CLUSTER._serialized_end=153
# @@protoc_insertion_point(module_scope)
